### PR TITLE
Add Dockerfile for FTB Infinity version 1.8.2

### PR DESCRIPTION
**Pull request by kmeisthax**
Sorry to bug you, but I just opened my FTB launcher to be greeted with a nice update message. So here's another Dockerfile. It appears to build but I need to figure out how to update the server I started yesterday without losing the data volume. (I'm a docker n00b.)

### CODE REVIEW

**Comment by dlord** [comment]
Please rebase this first on top of the latest master. Merge commit should not be part of the pull request.

**Comment by kmeisthax** [comment]
Manually rebased and ready to pull without merge flotsam

**Comment by dlord** [comment]
I am very specific about commit messages. And I just noticed that the commit message does not say what this is for.

Please edit the commit message to indicate what this is for.

**Comment by dlord** [comment]
Closing this due to non-conformance to commit message standards.

**Pull request closed without merging**
